### ISSUE TITLE
it doesnt work on esx

### ISSUE THREAD

**Issue by insrt66** [SolosV1/solos-jointroller#1]
config = {}

config.debug = true                                    -- Enable or disable debug mode (prints to console)

config.framework = {
    qb = false,                                          -- Set to true if using qbcore
    esx = true,                                        -- Set to true if using esx
    custom = false,                                     -- Set to true if using custom framework (requires modifications)
}

config.notify = function(msg, status) -- DON'T TOUCH THIS

    ---------   edit (or replace) below   -------------  
    
        lib.notify({
            description = msg,
            position = 'top',
            type = status, -- 'success', 'error', 'inform'
            style = {
                backgroundColor = 'rgba(0, 0, 0, 0.65)',
                color = 'white',
            },
        })
    
    ---------------------------------------------------
    
end

config.RollingPaper = {

    required = true,                                    -- Enable or disable requiring rolling paper to roll a joint

    item = 'weed_papers',                               -- Item name of the rolling paper (you can change this if you have a different rolling paper item than the one included)
    amount = 1,                                         -- Amount of rolling paper required each time joint roller is used
}       

config.strains = {      
    ['Marijuana Joint'] = {     
        joint = 'marijuana_joint',                -- Item name of the joint that player will receive
        effect = 'armor',                               -- Effect that will be applied to player when smoking this joint 
        receive = 1,                                    -- Amount of joints that player will receive after using joint roller
        required = {        
            item = 'weed_package',               -- Item name of the weed that is required to roll this joint (can be dry bud, bag of weed, whatever you want)
            amount = 1,                                 -- Amount of that item that is required to roll this joint
        },
    }
}

all items exist and shit but when i click button like done rolling it doesnt give item nor like it doesnt remove cursor from screen and doesnt stop the aniamtion and shit i setup all didnt change anything just config.

[script:vg-rolljjoint] joint roller used
[script:vg-rolljjoint] checking item    weed_package
[script:vg-rolljjoint] item     joint_roller    1
[script:vg-rolljjoint] item     weed_budclean   91
[script:vg-rolljjoint] item     weed_papers     6
[script:vg-rolljjoint] item     marijuana_joint 2
[script:vg-rolljjoint] item     weed_package    13
[script:vg-rolljjoint] checking item    weed_papers
[script:vg-rolljjoint] item     joint_roller    1
[script:vg-rolljjoint] item     weed_budclean   91
[script:vg-rolljjoint] item     weed_papers     6
[script:vg-rolljjoint] item     marijuana_joint 2
[script:vg-rolljjoint] item     weed_package    13

it gets to here in server

but in client it gets to message: Removing Rolling Paper: weed_papers   Amount: 1

**Comment by SolosV1** [comment]
cant change the name of the resource
